import type { IdescatSearchIndexEntry } from "../types.js";
import entries_afi from "./afi.js";
import entries_afic from "./afic.js";
import entries_censph from "./censph.js";
import entries_ceph from "./ceph.js";
import entries_comest from "./comest.js";
import entries_comtec from "./comtec.js";
import entries_covid from "./covid.js";
import entries_degurba from "./degurba.js";
import entries_e01 from "./e01.js";
import entries_e02 from "./e02.js";
import entries_e03 from "./e03.js";
import entries_ecl from "./ecl.js";
import entries_ee from "./ee.js";
import entries_eep from "./eep.js";
import entries_ep from "./ep.js";
import entries_eulp from "./eulp.js";
import entries_eut from "./eut.js";
import entries_fee from "./fee.js";
import entries_ilgu from "./ilgu.js";
import entries_irpf from "./irpf.js";
import entries_ispat from "./ispat.js";
import entries_ist from "./ist.js";
import entries_phre from "./phre.js";
import entries_piba from "./piba.js";
import entries_pibc from "./pibc.js";
import entries_pibt from "./pibt.js";
import entries_pmh from "./pmh.js";
import entries_proj from "./proj.js";
import entries_projl from "./projl.js";
import entries_projm from "./projm.js";
import entries_projpa from "./projpa.js";
import entries_rfdbc from "./rfdbc.js";

// biome-ignore format: generated search-index barrel
const entries: IdescatSearchIndexEntry[] = [...entries_afi, ...entries_afic, ...entries_censph, ...entries_ceph, ...entries_comest, ...entries_comtec, ...entries_covid, ...entries_degurba, ...entries_e01, ...entries_e02, ...entries_e03, ...entries_ecl, ...entries_ee, ...entries_eep, ...entries_ep, ...entries_eulp, ...entries_eut, ...entries_fee, ...entries_ilgu, ...entries_irpf, ...entries_ispat, ...entries_ist, ...entries_phre, ...entries_piba, ...entries_pibc, ...entries_pibt, ...entries_pmh, ...entries_proj, ...entries_projl, ...entries_projm, ...entries_projpa, ...entries_rfdbc];

export default entries;
export const generatedAt = "2026-04-26T17:33:08.557Z";
export const indexVersion = "generated-2026-04-26";
export const sourceCollectionUrls = ["https://api.idescat.cat/taules/v2?lang=es"];
