import type { IdescatSearchIndexEntry } from "../types.js";

// biome-ignore format: generated search-index entries
const entries: IdescatSearchIndexEntry[] = [
  {"statistics_id":"projm","node_id":"16137","table_id":"19440","label":"Población proyectada por escenario (base padrón 2021)","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Población proyectada por escenario (base padrón 2021)"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projm/16137/19440?lang=es"},
  {"statistics_id":"projm","node_id":"16139","table_id":"19441","label":"Población proyectada por sexo. Escenario bajo (base padrón 2021)","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Población proyectada por sexo. Escenario bajo (base padrón 2021)"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projm/16139/19441?lang=es"},
  {"statistics_id":"projm","node_id":"16140","table_id":"19442","label":"Población proyectada por sexo y edad. Escenario bajo (base padrón 2021)","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Población proyectada por sexo y edad. Escenario bajo (base padrón 2021)"},"geo_ids":["mun"],"source_url":"https://api.idescat.cat/taules/v2/projm/16140/19442?lang=es"},
  {"statistics_id":"projm","node_id":"16141","table_id":"19443","label":"Población proyectada por sexo y edad quinquenal. Escenario bajo (base padrón 2021)","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Población proyectada por sexo y edad quinquenal. Escenario bajo (base padrón 2021)"},"geo_ids":["mun"],"source_url":"https://api.idescat.cat/taules/v2/projm/16141/19443?lang=es"},
  {"statistics_id":"projm","node_id":"16142","table_id":"19478","label":"Población proyectada por sexo y grandes grupos de edad. Escenario bajo (base padrón 2021)","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Población proyectada por sexo y grandes grupos de edad. Escenario bajo (base padrón 2021)"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projm/16142/19478?lang=es"},
  {"statistics_id":"projm","node_id":"16144","table_id":"19445","label":"Población proyectada por sexo. Escenario medio (base padrón 2021)","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Población proyectada por sexo. Escenario medio (base padrón 2021)"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projm/16144/19445?lang=es"},
  {"statistics_id":"projm","node_id":"16145","table_id":"19446","label":"Población proyectada por sexo y edad. Escenario medio (base padrón 2021)","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Población proyectada por sexo y edad. Escenario medio (base padrón 2021)"},"geo_ids":["mun"],"source_url":"https://api.idescat.cat/taules/v2/projm/16145/19446?lang=es"},
  {"statistics_id":"projm","node_id":"16146","table_id":"19447","label":"Población proyectada por sexo y edad quinquenal. Escenario medio (base padrón 2021)","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Población proyectada por sexo y edad quinquenal. Escenario medio (base padrón 2021)"},"geo_ids":["mun"],"source_url":"https://api.idescat.cat/taules/v2/projm/16146/19447?lang=es"},
  {"statistics_id":"projm","node_id":"16147","table_id":"19479","label":"Población proyectada por sexo y grandes grupos de edad. Escenario medio (base padrón 2021)","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Población proyectada por sexo y grandes grupos de edad. Escenario medio (base padrón 2021)"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projm/16147/19479?lang=es"},
  {"statistics_id":"projm","node_id":"16149","table_id":"19449","label":"Población proyectada por sexo. Escenario alto (base padrón 2021)","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Población proyectada por sexo. Escenario alto (base padrón 2021)"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projm/16149/19449?lang=es"},
  {"statistics_id":"projm","node_id":"16150","table_id":"19450","label":"Población proyectada por sexo y edad. Escenario alto (base padrón 2021)","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Población proyectada por sexo y edad. Escenario alto (base padrón 2021)"},"geo_ids":["mun"],"source_url":"https://api.idescat.cat/taules/v2/projm/16150/19450?lang=es"},
  {"statistics_id":"projm","node_id":"16151","table_id":"19451","label":"Población proyectada por sexo y edad quinquenal. Escenario alto (base padrón 2021)","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Población proyectada por sexo y edad quinquenal. Escenario alto (base padrón 2021)"},"geo_ids":["mun"],"source_url":"https://api.idescat.cat/taules/v2/projm/16151/19451?lang=es"},
  {"statistics_id":"projm","node_id":"16152","table_id":"19480","label":"Población proyectada por sexo y grandes grupos de edad. Escenario alto (base padrón 2021)","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Población proyectada por sexo y grandes grupos de edad. Escenario alto (base padrón 2021)"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projm/16152/19480?lang=es"},
  {"statistics_id":"projm","node_id":"16154","table_id":"19453","label":"Componentes del crecimiento demográfico proyectado (base padrón 2021). Escenario bajo","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Componentes del crecimiento demográfico proyectado (base padrón 2021). Escenario bajo"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projm/16154/19453?lang=es"},
  {"statistics_id":"projm","node_id":"16155","table_id":"19454","label":"Componentes del crecimiento demográfico proyectado (base padrón 2021). Escenario medio","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Componentes del crecimiento demográfico proyectado (base padrón 2021). Escenario medio"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projm/16155/19454?lang=es"},
  {"statistics_id":"projm","node_id":"16156","table_id":"19455","label":"Componentes del crecimiento demográfico proyectado (base padrón 2021). Escenario alto","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Componentes del crecimiento demográfico proyectado (base padrón 2021). Escenario alto"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projm/16156/19455?lang=es"},
  {"statistics_id":"projm","node_id":"16236","table_id":"19595","label":"Población proyectada por escenario y grado de urbanización (base padrón 2021)","ancestor_labels":{"statistic":"Proyecciones de población municipales","node":"Población proyectada por escenario y grado de urbanización (base padrón 2021)"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/projm/16236/19595?lang=es"}
];

export default entries;
