import type { IdescatSearchIndexEntry } from "../types.js";

// biome-ignore format: generated search-index entries
const entries: IdescatSearchIndexEntry[] = [
  {"statistics_id":"ep","node_id":"10610","table_id":"11112","label":"Demographic changes in the population estimates","ancestor_labels":{"statistic":"Population Estimates","node":"Demographic changes in the population estimates. Total"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/ep/10610/11112?lang=en"},
  {"statistics_id":"ep","node_id":"10611","table_id":"11113","label":"Demographic changes in the population estimates. Men","ancestor_labels":{"statistic":"Population Estimates","node":"Demographic changes in the population estimates. Men"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/ep/10611/11113?lang=en"},
  {"statistics_id":"ep","node_id":"10612","table_id":"11114","label":"Demographic changes in the population estimates. Women","ancestor_labels":{"statistic":"Population Estimates","node":"Demographic changes in the population estimates. Women"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/ep/10612/11114?lang=en"},
  {"statistics_id":"ep","node_id":"17363","table_id":"20891","label":"Population. By sex and age in large age groups","ancestor_labels":{"statistic":"Population Estimates","node":"Population. By sex and age in large age groups"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/ep/17363/20891?lang=en"},
  {"statistics_id":"ep","node_id":"9122","table_id":"10002","label":"Population. By sex","ancestor_labels":{"statistic":"Population Estimates","node":"Population. By sex"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/ep/9122/10002?lang=en"},
  {"statistics_id":"ep","node_id":"9123","table_id":"10007","label":"Population. By sex and age (S2/1986–S2/2011)","ancestor_labels":{"statistic":"Population Estimates","node":"Population. By sex and age"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/ep/9123/10007?lang=en"},
  {"statistics_id":"ep","node_id":"9123","table_id":"10008","label":"Population. By sex and age (S1/1981–S1/1986)","ancestor_labels":{"statistic":"Population Estimates","node":"Population. By sex and age"},"geo_ids":["at","cat","com","prov"],"source_url":"https://api.idescat.cat/taules/v2/ep/9123/10008?lang=en"},
  {"statistics_id":"ep","node_id":"9123","table_id":"20149","label":"Population. By sex and age (S1/2012–S1/2025)","ancestor_labels":{"statistic":"Population Estimates","node":"Population. By sex and age"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/ep/9123/20149?lang=en"},
  {"statistics_id":"ep","node_id":"9123","table_id":"21460","label":"Population. By sex and age year by year (S2/2025)","ancestor_labels":{"statistic":"Population Estimates","node":"Population. By sex and age"},"geo_ids":["cat","prov"],"source_url":"https://api.idescat.cat/taules/v2/ep/9123/21460?lang=en"},
  {"statistics_id":"ep","node_id":"9124","table_id":"10009","label":"Population. By sex and five year age group (S2/1986–S2/2011)","ancestor_labels":{"statistic":"Population Estimates","node":"Population. By sex and five year age group"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/ep/9124/10009?lang=en"},
  {"statistics_id":"ep","node_id":"9124","table_id":"10011","label":"Population. By sex and five year age group (S1/1981–S1/1986)","ancestor_labels":{"statistic":"Population Estimates","node":"Population. By sex and five year age group"},"geo_ids":["at","cat","com","prov"],"source_url":"https://api.idescat.cat/taules/v2/ep/9124/10011?lang=en"},
  {"statistics_id":"ep","node_id":"9124","table_id":"20150","label":"Population. By sex and five-year age group (S1/2012–)","ancestor_labels":{"statistic":"Population Estimates","node":"Population. By sex and five year age group"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/ep/9124/20150?lang=en"}
];

export default entries;
