import type { IdescatSearchIndexEntry } from "../types.js";

// biome-ignore format: generated search-index entries
const entries: IdescatSearchIndexEntry[] = [
  {"statistics_id":"projpa","node_id":"14859","table_id":"15719","label":"Projected active population by sex and scenario (base 2021)","ancestor_labels":{"statistic":"Active Population Projections","node":"Projected active population by sex and scenario"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projpa/14859/15719?lang=en"},
  {"statistics_id":"projpa","node_id":"14863","table_id":"15720","label":"Projected active population by sex and age group. Low scenario (base 2021)","ancestor_labels":{"statistic":"Active Population Projections","node":"Projected active population by sex and age group. Low scenario"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projpa/14863/15720?lang=en"},
  {"statistics_id":"projpa","node_id":"14864","table_id":"15745","label":"Projected active population by sex and age group. Medium scenario (base 2021)","ancestor_labels":{"statistic":"Active Population Projections","node":"Projected active population by sex and age group. Medium scenario"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projpa/14864/15745?lang=en"},
  {"statistics_id":"projpa","node_id":"14865","table_id":"15747","label":"Projected active population by sex and age group. High scenario (base 2021)","ancestor_labels":{"statistic":"Active Population Projections","node":"Projected active population by sex and age group. High scenario"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projpa/14865/15747?lang=en"},
  {"statistics_id":"projpa","node_id":"14866","table_id":"15754","label":"Projected active population by sex and five year age group. Low scenario (base 2021)","ancestor_labels":{"statistic":"Active Population Projections","node":"Projected active population by sex and five-year age group. Low scenario"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projpa/14866/15754?lang=en"},
  {"statistics_id":"projpa","node_id":"14867","table_id":"15755","label":"Projected active population by sex and five year age group. Medium scenario (base 2021)","ancestor_labels":{"statistic":"Active Population Projections","node":"Projected active population by sex and five-year age group. Medium scenario"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projpa/14867/15755?lang=en"},
  {"statistics_id":"projpa","node_id":"14868","table_id":"15756","label":"Projected active population by sex and five year age group. High scenario (base 2021)","ancestor_labels":{"statistic":"Active Population Projections","node":"Projected active population by sex and five-year age group. High scenario"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projpa/14868/15756?lang=en"},
  {"statistics_id":"projpa","node_id":"14869","table_id":"15721","label":"Projected activity rate by scenario (base 2021)","ancestor_labels":{"statistic":"Active Population Projections","node":"Projected activity rate by scenario"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projpa/14869/15721?lang=en"},
  {"statistics_id":"projpa","node_id":"14870","table_id":"15751","label":"Projected activity rate by sex. Low scenario (base 2021)","ancestor_labels":{"statistic":"Active Population Projections","node":"Projected activity rate by sex. Low scenario"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projpa/14870/15751?lang=en"},
  {"statistics_id":"projpa","node_id":"14871","table_id":"15752","label":"Projected activity rate by sex. Medium scenario (base 2021)","ancestor_labels":{"statistic":"Active Population Projections","node":"Projected activity rate by sex. Medium scenario"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projpa/14871/15752?lang=en"},
  {"statistics_id":"projpa","node_id":"14872","table_id":"15753","label":"Projected activity rate by sex. High scenario (base 2021)","ancestor_labels":{"statistic":"Active Population Projections","node":"Projected activity rate by sex. High scenario"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projpa/14872/15753?lang=en"},
  {"statistics_id":"projpa","node_id":"14873","table_id":"15722","label":"Projected activity rate by sex and age group. Low scenario (base 2021)","ancestor_labels":{"statistic":"Active Population Projections","node":"Projected activity rate by sex and age group. Low scenario"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projpa/14873/15722?lang=en"},
  {"statistics_id":"projpa","node_id":"14874","table_id":"15749","label":"Projected activity rate by sex and age group. Medium scenario (base 2021)","ancestor_labels":{"statistic":"Active Population Projections","node":"Projected activity rate by sex and age group. Medium scenario"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projpa/14874/15749?lang=en"},
  {"statistics_id":"projpa","node_id":"14875","table_id":"15750","label":"Projected activity rate by sex and age group. High scenario (base 2021)","ancestor_labels":{"statistic":"Active Population Projections","node":"Projected activity rate by sex and age group. High scenario"},"geo_ids":["at","cat","com","mun","prov"],"source_url":"https://api.idescat.cat/taules/v2/projpa/14875/15750?lang=en"}
];

export default entries;
