import type { IdescatSearchIndexEntry } from "../types.js";

// biome-ignore format: generated search-index entries
const entries: IdescatSearchIndexEntry[] = [
  {"statistics_id":"fee","node_id":"21934","table_id":"23172","label":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per sector d'activitat econòmica de l'empresa","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per sector d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21934/23172?lang=ca"},
  {"statistics_id":"fee","node_id":"21935","table_id":"24523","label":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per sector d'activitat econòmica de l'empresa. Percentatge sobre el total d'empreses amb establiments a Catalunya","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per sector d'activitat econòmica de l'empresa. Percentatge sobre el total d'empreses amb establiments a Catalunya"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21935/24523?lang=ca"},
  {"statistics_id":"fee","node_id":"21936","table_id":"24547","label":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per branca d'activitat econòmica de l'empresa","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per branca d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21936/24547?lang=ca"},
  {"statistics_id":"fee","node_id":"21937","table_id":"24548","label":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per branca d'activitat econòmica de l'empresa. Percentatge sobre el total d'empreses amb establiments a Catalunya","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per branca d'activitat econòmica de l'empresa. Percentatge sobre el total d'empreses amb establiments a Catalunya"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21937/24548?lang=ca"},
  {"statistics_id":"fee","node_id":"21938","table_id":"21264","label":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per país de l'empresa matriu","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per país de l'empresa matriu"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21938/21264?lang=ca"},
  {"statistics_id":"fee","node_id":"21939","table_id":"24989","label":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per grandària i sector d'activitat econòmica de l'empresa","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per grandària i sector d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21939/24989?lang=ca"},
  {"statistics_id":"fee","node_id":"21940","table_id":"24990","label":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per grandària i sector d'activitat econòmica de l'empresa. Percentatge sobre el total d'empreses amb establiments a Catalunya","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per grandària i sector d'activitat econòmica de l'empresa. Percentatge sobre el total d'empreses amb establiments a Catalunya"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21940/24990?lang=ca"},
  {"statistics_id":"fee","node_id":"21941","table_id":"24991","label":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per zona geogràfica de l'empresa matriu","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals resultats per zona geogràfica de l'empresa matriu i sector d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21941/24991?lang=ca"},
  {"statistics_id":"fee","node_id":"21943","table_id":"26432","label":"Filials d'empreses estrangeres i empreses amb establiments a Catalunya. Principals indicadors per sector d'activitat econòmica de l'empresa","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres i empreses amb establiments a Catalunya. Principals indicadors per sector d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21943/26432?lang=ca"},
  {"statistics_id":"fee","node_id":"21945","table_id":"26433","label":"Filials d'empreses estrangeres i empreses amb establiments a Catalunya. Principals indicadors per branca d'activitat econòmica de l'empresa","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres i empreses amb establiments a Catalunya. Principals indicadors per branca d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21945/26433?lang=ca"},
  {"statistics_id":"fee","node_id":"21947","table_id":"21267","label":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals indicadors per país de l'empresa matriu","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres i empreses amb establiments a Catalunya. Principals indicadors per país de l'empresa matriu"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21947/21267?lang=ca"},
  {"statistics_id":"fee","node_id":"21948","table_id":"26434","label":"Filials d'empreses estrangeres i empreses amb establiments a Catalunya. Principals indicadors per grandària i sector d'activitat econòmica de l'empresa","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres i empreses amb establiments a Catalunya. Principals indicadors per grandària i sector d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21948/26434?lang=ca"},
  {"statistics_id":"fee","node_id":"21950","table_id":"24994","label":"Filials d'empreses estrangeres amb establiments a Catalunya. Principals indicadors per zona geogràfica de l'empresa matriu i sector d'activitat econòmica de l'empresa","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres i empreses amb establiments a Catalunya. Principals indicadors per zona geogràfica de l'empresa matriu i sector d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21950/24994?lang=ca"},
  {"statistics_id":"fee","node_id":"21953","table_id":"24526","label":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per sector d'activitat econòmica de l'empresa","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per sector d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21953/24526?lang=ca"},
  {"statistics_id":"fee","node_id":"21954","table_id":"24527","label":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per sector d'activitat econòmica de l'empresa. Percentatge sobre el total d'empreses amb seu a Catalunya","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per sector d'activitat econòmica de l'empresa. Percentatge sobre el total d'empreses amb seu a Catalunya"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21954/24527?lang=ca"},
  {"statistics_id":"fee","node_id":"21955","table_id":"24551","label":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per branca d'activitat econòmica de l'empresa","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per branca d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21955/24551?lang=ca"},
  {"statistics_id":"fee","node_id":"21956","table_id":"24552","label":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per branca d'activitat econòmica de l'empresa. Percentatge sobre el total d'empreses amb seu a Catalunya","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per branca d'activitat econòmica de l'empresa. Percentatge sobre el total d'empreses amb seu a Catalunya"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21956/24552?lang=ca"},
  {"statistics_id":"fee","node_id":"21957","table_id":"21279","label":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per país de l'empresa matriu","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per país de l'empresa matriu"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21957/21279?lang=ca"},
  {"statistics_id":"fee","node_id":"21958","table_id":"24995","label":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per grandària i sector d'activitat econòmica de l'empresa","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per grandària i sector d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21958/24995?lang=ca"},
  {"statistics_id":"fee","node_id":"21959","table_id":"24996","label":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per grandària i sector d'activitat econòmica de l'empresa. Percentatge sobre el total d'empreses amb seu a Catalunya","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per grandària i sector d'activitat econòmica de l'empresa. Percentatge sobre el total d'empreses amb seu a Catalunya"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21959/24996?lang=ca"},
  {"statistics_id":"fee","node_id":"21960","table_id":"24997","label":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per zona geogràfica de l'empresa matriu i sector d'activitat econòmica de l'empresa","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres amb seu a Catalunya. Principals resultats per zona geogràfica de l'empresa matriu i sector d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21960/24997?lang=ca"},
  {"statistics_id":"fee","node_id":"21962","table_id":"26435","label":"Filials d'empreses estrangeres i empreses amb seu a Catalunya. Principals indicadors per sector d'activitat econòmica de l'empresa","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres i empreses amb seu a Catalunya. Principals indicadors per sector d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21962/26435?lang=ca"},
  {"statistics_id":"fee","node_id":"21964","table_id":"26436","label":"Filials d'empreses estrangeres i empreses amb seu a Catalunya. Principals indicadors per branca d'activitat econòmica de l'empresa","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres i empreses amb seu a Catalunya. Principals indicadors per branca d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21964/26436?lang=ca"},
  {"statistics_id":"fee","node_id":"21966","table_id":"21282","label":"Filials d'empreses estrangeres amb seu a Catalunya. Principals indicadors per país de l'empresa matriu","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres i empreses amb seu a Catalunya. Principals indicadors per país de l'empresa matriu"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21966/21282?lang=ca"},
  {"statistics_id":"fee","node_id":"21967","table_id":"26437","label":"Filials d'empreses estrangeres i empreses amb seu a Catalunya. Principals indicadors per grandària i sector d'activitat econòmica de l'empresa","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeres i empreses amb seu a Catalunya. Principals indicadors per grandària i sector d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21967/26437?lang=ca"},
  {"statistics_id":"fee","node_id":"21969","table_id":"25000","label":"Filials d'empreses estrangeres amb seu a Catalunya. Principals indicadors per zona geogràfica de l'empresa matriu i sector d'activitat econòmica de l'empresa","ancestor_labels":{"statistic":"Estadística de filials d'empreses estrangeres","node":"Filials d'empreses estrangeresi empreses amb seu a Catalunya. Principals indicadors per zona geogràfica de l'empresa matriu i sector d'activitat econòmica de l'empresa"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/fee/21969/25000?lang=ca"}
];

export default entries;
