import type { IdescatSearchIndexEntry } from "../types.js";

// biome-ignore format: generated search-index entries
const entries: IdescatSearchIndexEntry[] = [
  {"statistics_id":"pibc","node_id":"13830","table_id":"14779","label":"Producte interior brut","ancestor_labels":{"statistic":"Producte interior brut territorial","node":"PIB i PIB per habitant. Revisió estadística 2019"},"geo_ids":["at","cat","com","mun"],"source_url":"https://api.idescat.cat/taules/v2/pibc/13830/14779?lang=ca"},
  {"statistics_id":"pibc","node_id":"13831","table_id":"14780","label":"Valor afegit brut. Per sectors d'activitat","ancestor_labels":{"statistic":"Producte interior brut territorial","node":"Valor afegit brut. Per sectors d'activitat. Revisió estadística 2019"},"geo_ids":["at","cat","com","mun"],"source_url":"https://api.idescat.cat/taules/v2/pibc/13831/14780?lang=ca"},
  {"statistics_id":"pibc","node_id":"13833","table_id":"14782","label":"Valor afegit brut de la indústria. Per branques d'activitat","ancestor_labels":{"statistic":"Producte interior brut territorial","node":"Valor afegit brut de la indústria. Per branques d'activitat. Revisió estadística 2019"},"geo_ids":["at","cat","com","mun"],"source_url":"https://api.idescat.cat/taules/v2/pibc/13833/14782?lang=ca"},
  {"statistics_id":"pibc","node_id":"13835","table_id":"14784","label":"Valor afegit brut dels serveis. Per branques d'activitat","ancestor_labels":{"statistic":"Producte interior brut territorial","node":"Valor afegit brut dels serveis. Per branques d'activitat. Revisió estadística 2019"},"geo_ids":["at","cat","com","mun"],"source_url":"https://api.idescat.cat/taules/v2/pibc/13835/14784?lang=ca"},
  {"statistics_id":"pibc","node_id":"21925","table_id":"26069","label":"Producte interior brut","ancestor_labels":{"statistic":"Producte interior brut territorial","node":"PIB i PIB per habitant. Revisió estadística 2024"},"geo_ids":["at","cat","com","mun"],"source_url":"https://api.idescat.cat/taules/v2/pibc/21925/26069?lang=ca"},
  {"statistics_id":"pibc","node_id":"21926","table_id":"26070","label":"Valor afegit brut. Per sectors d'activitat","ancestor_labels":{"statistic":"Producte interior brut territorial","node":"Valor afegit brut. Per sectors d'activitat. Revisió estadística 2024"},"geo_ids":["at","cat","com","mun"],"source_url":"https://api.idescat.cat/taules/v2/pibc/21926/26070?lang=ca"},
  {"statistics_id":"pibc","node_id":"21927","table_id":"26071","label":"Valor afegit brut de la indústria. Per branques d'activitat","ancestor_labels":{"statistic":"Producte interior brut territorial","node":"Valor afegit brut de la indústria. Per branques d'activitat. Revisió estadística 2024"},"geo_ids":["at","cat","com","mun"],"source_url":"https://api.idescat.cat/taules/v2/pibc/21927/26071?lang=ca"},
  {"statistics_id":"pibc","node_id":"21928","table_id":"26072","label":"Valor afegit brut dels serveis. Per branques d'activitat","ancestor_labels":{"statistic":"Producte interior brut territorial","node":"Valor afegit brut dels serveis. Per branques d'activitat. Revisió estadística 2024"},"geo_ids":["at","cat","com","mun"],"source_url":"https://api.idescat.cat/taules/v2/pibc/21928/26072?lang=ca"}
];

export default entries;
