import type { IdescatSearchIndexEntry } from "../types.js";

// biome-ignore format: generated search-index entries
const entries: IdescatSearchIndexEntry[] = [
  {"statistics_id":"pibt","node_id":"13077","table_id":"15840","label":"Producte interior brut a preus corrents. Oferta. Dades corregides d'estacionalitat","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut a preus corrents. Oferta. Dades corregides d'estacionalitat. Revisió estadística 2019"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/13077/15840?lang=ca"},
  {"statistics_id":"pibt","node_id":"13078","table_id":"15842","label":"Producte interior brut en volum. Oferta. Dades corregides d'estacionalitat","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut en volum. Oferta. Dades corregides d'estacionalitat. Revisió estadística 2019"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/13078/15842?lang=ca"},
  {"statistics_id":"pibt","node_id":"13080","table_id":"15844","label":"Producte interior brut a preus corrents. Oferta. Dades brutes","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut a preus corrents. Oferta. Dades brutes. Revisió estadística 2019"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/13080/15844?lang=ca"},
  {"statistics_id":"pibt","node_id":"13081","table_id":"15849","label":"Producte interior brut en volum. Oferta. Dades brutes","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut en volum. Oferta. Dades brutes. Revisió estadística 2019"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/13081/15849?lang=ca"},
  {"statistics_id":"pibt","node_id":"21129","table_id":"24938","label":"Producte interior brut a preus corrents. Oferta. Dades corregides d'estacionalitat","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut a preus corrents. Oferta. Dades corregides d'estacionalitat. Revisió estadística 2024"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/21129/24938?lang=ca"},
  {"statistics_id":"pibt","node_id":"21130","table_id":"24940","label":"Producte interior brut en volum. Oferta. Dades corregides d'estacionalitat","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut en volum. Oferta. Dades corregides d'estacionalitat. Revisió estadística 2024"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/21130/24940?lang=ca"},
  {"statistics_id":"pibt","node_id":"21132","table_id":"24942","label":"Producte interior brut a preus corrents. Oferta. Dades brutes","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut a preus corrents. Oferta. Dades brutes. Revisió estadística 2024"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/21132/24942?lang=ca"},
  {"statistics_id":"pibt","node_id":"21133","table_id":"24944","label":"Producte interior brut en volum. Oferta. Dades brutes","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut en volum. Oferta. Dades brutes. Revisió estadística 2024"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/21133/24944?lang=ca"},
  {"statistics_id":"pibt","node_id":"21651","table_id":"15841","label":"Producte interior brut a preus corrents. Demanda. Dades corregides d'estacionalitat","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut a preus corrents. Demanda. Dades corregides d'estacionalitat. Revisió estadística 2019"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/21651/15841?lang=ca"},
  {"statistics_id":"pibt","node_id":"21652","table_id":"24939","label":"Producte interior brut a preus corrents. Demanda. Dades corregides d'estacionalitat","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut a preus corrents. Demanda. Dades corregides d'estacionalitat. Revisió estadística 2024"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/21652/24939?lang=ca"},
  {"statistics_id":"pibt","node_id":"21653","table_id":"15843","label":"Producte interior brut en volum. Demanda. Dades corregides d'estacionalitat","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut en volum. Demanda. Dades corregides d'estacionalitat. Revisió estadística 2019"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/21653/15843?lang=ca"},
  {"statistics_id":"pibt","node_id":"21654","table_id":"24941","label":"Producte interior brut en volum. Demanda. Dades corregides d'estacionalitat","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut en volum. Demanda. Dades corregides d'estacionalitat. Revisió estadística 2024"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/21654/24941?lang=ca"},
  {"statistics_id":"pibt","node_id":"21655","table_id":"15845","label":"Producte interior brut a preus corrents. Demanda. Dades brutes","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut a preus corrents. Demanda. Dades brutes. Revisió estadística 2019"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/21655/15845?lang=ca"},
  {"statistics_id":"pibt","node_id":"21656","table_id":"24943","label":"Producte interior brut a preus corrents. Demanda. Dades brutes","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut a preus corrents. Demanda. Dades brutes. Revisió estadística 2024"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/21656/24943?lang=ca"},
  {"statistics_id":"pibt","node_id":"21657","table_id":"15850","label":"Producte interior brut en volum. Demanda. Dades brutes","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut a preus corrents. Demanda. Dades brutes. Revisió estadística 2019"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/21657/15850?lang=ca"},
  {"statistics_id":"pibt","node_id":"21658","table_id":"24945","label":"Producte interior brut en volum. Demanda. Dades brutes","ancestor_labels":{"statistic":"Comptabilitat trimestral","node":"Producte interior brut a preus corrents. Demanda. Dades brutes. Revisió estadística 2024"},"geo_ids":["cat"],"source_url":"https://api.idescat.cat/taules/v2/pibt/21658/24945?lang=ca"}
];

export default entries;
